file = open("Exception.py", "r")